#include <mach/gp_ppu.h>

//PPU MODULE
extern signed int gplib_ppu_init(PPU_REGISTER_SETS *p_register_set);
extern signed int gplib_ppu_enable_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_char0_transparent_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_bottom_up_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_vga_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_non_interlace_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_frame_buffer_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int enable, unsigned int select);
extern signed int gplib_ppu_fb_format_set(PPU_REGISTER_SETS *p_register_set, unsigned int format, unsigned int mono);
extern signed int gplib_ppu_save_rom_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_resolution_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_yuv_type_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_color_mapping_set(PPU_REGISTER_SETS *p_register_set, unsigned int enable, unsigned int value);
extern signed int gplib_ppu_tft_long_burst_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_blend4_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_rgb565_transparent_color_set(PPU_REGISTER_SETS *p_register_set, unsigned int enable, unsigned int value);
extern signed int gplib_ppu_fade_effect_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_window_set(PPU_REGISTER_SETS *p_register_set, unsigned int window_index, unsigned int window_x, unsigned int window_y);
extern signed int gplib_ppu_palette_type_set(PPU_REGISTER_SETS *p_register_set, unsigned int p1024, unsigned int type);
extern signed int gplib_ppu_palette_ram_ptr_set(PPU_REGISTER_SETS *p_register_set, unsigned int bank, unsigned int value);
extern signed int gplib_ppu_frame_buffer_add(PPU_REGISTER_SETS *p_register_set, unsigned int buffer);
extern signed int gplib_ppu_SPADDRX2_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_go_without_wait(PPU_REGISTER_SETS *p_register_set);
extern signed int gplib_ppu_go(PPU_REGISTER_SETS *p_register_set);
extern signed int gplib_ppu_go_and_wait_done(PPU_REGISTER_SETS *p_register_set);
extern signed int gplib_ppu_dual_blend_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_free_size_set(PPU_REGISTER_SETS *p_register_set, unsigned short INTL, unsigned short H_size, unsigned short V_size);
extern signed int gplib_ppu_text_rgba_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_text_alpha_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_rgba_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_text_new_specialbmp_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_text_new_compression_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_delgo_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_tftvtq_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_tv_long_burst_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_interpolation_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int value, unsigned int set_value);
extern signed int gplib_ppu_frame_buffer_output_fifo_set(PPU_REGISTER_SETS *p_register_set, unsigned short line_start, unsigned short fifo_type, unsigned short addr_offset);
extern signed int gplib_ppu_fifo_go_and_wait_done(void);
extern signed int gplib_ppu_frame_buffer_get(void);
extern signed int gplib_ppu_frame_buffer_release(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_long_burst_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);

//PPU TEXT MODULE
extern signed int gplib_ppu_text_init(PPU_REGISTER_SETS *p_register_set, unsigned int text_index);
extern signed int gplib_ppu_text_enable_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_compress_disable_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_text_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_direct_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_text_wallpaper_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_attribute_source_select(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_horizontal_move_enable_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_size_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_character_size_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int txn_hs, unsigned int txn_vs);
extern signed int gplib_ppu_text_bitmap_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_color_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int rgb_mode, unsigned int color);
extern signed int gplib_ppu_text_palette_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int bank, unsigned int palette_idx);
extern signed int gplib_ppu_text_segment_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_calculate_number_array(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int photo_width, unsigned int photo_height, unsigned int data_ptr);
extern signed int gplib_ppu_text_number_array_ptr_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_position_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int pos_x, unsigned int pos_y);
extern signed int gplib_ppu_text_offset_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int offset_x, unsigned int offset_y);
extern signed int gplib_ppu_text_depth_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_blend_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int enable, unsigned int mode, unsigned int value);
extern signed int gplib_ppu_text_flip_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_sine_cosine_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned short r_sine, unsigned short r_cosine);
extern signed int gplib_ppu_text_window_select(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_special_effect_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_vertical_compress_set(PPU_REGISTER_SETS *p_register_set, unsigned int value, unsigned int offset, unsigned int step);
extern signed int gplib_ppu_text_horizontal_move_ptr_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_text1_horizontal_compress_ptr_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_text_rotate_zoom_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, signed short angle,  float factor_k);
extern signed int gplib_ppu_text3_25d_set(PPU_REGISTER_SETS *p_register_set, signed short angle, float *factor_ptr);
extern signed int gplib_ppu_text3_25d_y_compress_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int Text25D_CosSineBuf_set(PPU_REGISTER_SETS *p_register_set, unsigned int CosSineBuf);
extern signed int gplib_ppu_text_interpolation_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int gplib_ppu_text_color_mask_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int text_index, unsigned int value);
extern signed int Update_Number_Array(PnTX_Num_Arr text_info);
extern signed int load_text_data(PPU_REGISTER_SETS *p_register_set,unsigned int text_index,nTX_image_info *text_info);

//PPU SPRITE MODULE
extern signed int gplib_ppu_sprite_init(PPU_REGISTER_SETS *p_register_set);
extern signed int gplib_ppu_sprite_enable_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_coordinate_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_blend_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_direct_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_zoom_enable_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_rotate_enable_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_mosaic_enable_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_number_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_special_effect_enable_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_color_dither_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_25d_mode_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_window_enable_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_segment_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_attribute_ram_ptr_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_sfr_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_large_sprite_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_interpolation_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_group_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_cdm_attribute_enable_set(SpN_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_sprite_fraction_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_extend_attribute_ram_ptr_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_exsprite_enable_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_exsprite_cdm_enable_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_exsprite_interpolation_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_exsprite_large_size_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_exsprite_group_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_exsprite_fraction_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_exsprite_number_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_exsprite_start_address_set(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern signed int gplib_ppu_sprite_attribute_2d_position_set(SpN_RAM *sprite_attr, signed short x0, signed short y0);
extern signed int gplib_ppu_sprite_attribute_25d_position_set(SpN_RAM *out, POS_STRUCT_PTR in);
extern signed int gplib_ppu_sprite_attribute_rotate_set(SpN_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_sprite_attribute_zoom_set(SpN_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_sprite_attribute_color_set(SpN_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_sprite_attribute_flip_set(SpN_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_sprite_attribute_character_size_set(SpN_RAM *sprite_attr, unsigned int hs, unsigned int vs);
extern signed int gplib_ppu_sprite_attribute_palette_set(SpN_RAM *sprite_attr, unsigned int bank, unsigned int palette_idx);
extern signed int gplib_ppu_sprite_attribute_depth_set(SpN_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_sprite_attribute_blend64_set(SpN_RAM *sprite_attr, unsigned int enable, unsigned int value);
extern signed int gplib_ppu_sprite_attribute_blend16_set(SpN_RAM *sprite_attr, unsigned int enable, unsigned int value);
extern signed int gplib_ppu_sprite_attribute_window_set(SpN_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_sprite_attribute_mosaic_set(SpN_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_sprite_attribute_character_number_set(SpN_RAM *sprite_attr, unsigned int spnum);
extern signed int gplib_ppu_exsprite_group_attribute_set(SpN_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_sprite_group_attribute_set(SpN_EX_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_exsprite_large_size_attribute_set(SpN_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_sprite_large_size_attribute_set(SpN_EX_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_exsprite_interpolation_attribute_set(SpN_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_sprite_interpolation_attribute_set(SpN_EX_RAM *sprite_attr, unsigned int value);
extern signed int gplib_ppu_sprite_cdm_attribute_set(SpN_RAM *sprite_attr, unsigned int value ,CDM_STRUCT_PTR in);
extern signed int gplib_ppu_sprite_color_mask_attribute_set(SpN_EX_RAM *sprite_attr, unsigned int value);
extern signed int set_sprite_init(unsigned int sprite_number,unsigned int sprite_ptr);
extern signed int set_sprite_display_init(unsigned int sprite_number, signed short sprite_pos_x, signed short sprite_pos_y, unsigned int sprite_ptr);
extern signed int set_sprite_image_number(unsigned int sprite_number,unsigned int sprite_ptr);
extern signed int set_sprite_disable(unsigned int sprite_number);
extern signed int Get_sprite_image_info(unsigned int sprite_number,SpN_ptr *sprite_ptr);
extern signed int paint_ppu_spriteram(PPU_REGISTER_SETS *p_register_set,Sprite_Coordinate_Mode display_mode, Coordinate_Change_Mode coordinate_mode, unsigned int sprite_number);
extern unsigned int gplib_ppu_malloc_spriteram(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern unsigned int gplib_ppu_malloc_sprite_ex_ram(PPU_REGISTER_SETS *p_register_set, unsigned int value);
extern void clean_cache (unsigned int start,unsigned int num);
// LINUX WAIT API
extern signed int gblib_ppu_wait_poll(unsigned int Timeout_sec,unsigned int Timeout_usec);
