# ###############################################################
# Sensors
# ###############################################################

#obj-m += ov_9655.o
#obj-m += ov_3640.o
#obj-m += gc_0307.o
#obj-m += cdsp_ov7670.o
#obj-m += cdsp_ov3640.o
#obj-m += cdsp_ov5642.o
#obj-m += tvp_5150.o

#obj-m += cdsp_mt9d112.o
#obj-m += mt_9d112.o
#obj-m += cdsp_gt2005.o
obj-m += ov_2643.o
obj-m += ss_A66.o
#obj-m += ss_6AA.o
obj-m += ss_6AA_mipi.o
