# ###############################################################
# LCD panels
# ###############################################################

obj-m += lcd_auo_A043FL01.o
obj-m += lcd_innolux_AT070TN83.o
obj-m += lcd_innolux_AT070TN92.o
obj-m += lcd_hannstar_HSD070IDW1.o
obj-m += lcd_hannstar_HSD070IDW1_RGB666.o
obj-m += lcd_tpo_TD070WGCB2.o
obj-m += lcd_hannstar_HSD089IFW1.o
obj-m += lcd_adl_A070SWN01A0.o
obj-m += lcd_innolux_YT70F10_RGB666.o