#
# Makefile for the nand
#
obj-m	+= gp_nand_module.o

gp_nand_module-objs := \
	spmp_nf_api.o	\
	spmp8k_nand.o	\
	champ/nand_FDisk.o	\
	champ/NF_Rom_Cache.o	\
	champ/storage_op.o	\
	NFTL/fifo.o	\
	NFTL/nand.o	\
	NFTL/nand_badblk.o	\
	NFTL/nand_pgbase.o	\
	NFTL/nftl.o	\
	hal/bch.o	\
	hal/bch_s336.o	\
	hal/hal_base.o	\
	hal/nf_s330.o
