# ###############################################################
# LCD1 panels
# ###############################################################

obj-m += lcd_hannstar_HSD070IDW1_tft1.o
#obj-m += lcd_innolux_AT070TN92_tft1.o
obj-m += lcd_auo_A043FL01_tft1.o