/*
	The content of this file need to update if wavetable was updated
	Otherwise, this index may not correct
*/

#ifndef AUDIOINSTRUMENTLIST_H
#define AUDIOINSTRUMENTLIST_H

typedef enum {
	AUDIO_AC_PIANO = 0,
	AUDIO_RHOD_PIANO,
	AUDIO_HARPSICHORD,
	AUDIO_GLOCKENSPIEL,
	AUDIO_MUSICBOX,
	AUDIO_VIBRAPHONE,
	AUDIO_XYLOPHONE,
	AUDIO_ROCKORGAN,
	AUDIO_ACCORDIAN,
	AUDIO_GTNYLON,
	AUDIO_GTJAZZ,
	AUDIO_GTDISTORTION,
	AUDIO_ACOUSTICBASS,
	AUDIO_BASSFINGER,
	AUDIO_BASSSYNTH,
	AUDIO_VIOLIN,
	AUDIO_PIZZICATOSTRINGS,
	AUDIO_STRINGENSEMBLE,
	AUDIO_ORCHESTRALHARP,
	AUDIO_TIMPANI,
	AUDIO_ORCHESTRAHIT,
	AUDIO_TRUMPET,
	AUDIO_TROMBONE,
	AUDIO_TUBA,
	AUDIO_FRENCHHORN,
	AUDIO_BRASSSECTION,
	AUDIO_ALTOSAX,
	AUDIO_BASSOON,
	AUDIO_CLARINET,
	AUDIO_FLUTE,
	AUDIO_RECORDER,
	AUDIO_LEADSQUARE,
	AUDIO_LEADSAWTOOTH,
	AUDIO_PAD8SWEEP,
	AUDIO_FX4ATMOSPHERE,
	AUDIO_FX5BRIGHTNESS,
	AUDIO_BANJO,
	AUDIO_KOTO,
	AUDIO_STEELDRUMS,
	AUDIO_WOODBLOCK,
	AUDIO_REVERSECYMBAL,
	AUDIO_TOTAL_MELO_COUNT
} AudioMeloIns;

typedef enum {
	AUDIO_DRUM29 = 0,
	AUDIO_BASSDRUM,
	AUDIO_SIDESTICK,
	AUDIO_ACOUSTICSNARE,
	AUDIO_HANDCLAP,
	AUDIO_ELECTRICSNARE,
	AUDIO_CLOSEDHIHAT,
	AUDIO_HIGHFLOORTOM,
	AUDIO_OPENHIHAT,
	AUDIO_LOWMIDTOM,
	AUDIO_CRASHCYMBAL,
	AUDIO_HIGHTOM,
	AUDIO_RIDECYMBAL,
	AUDIO_CHINESECYMBAL,
	AUDIO_RIDEBELL,
	AUDIO_TAMBOURINE,
	AUDIO_COWBELL,
	AUDIO_VIBRASLAP,
	AUDIO_HIBONGO,
	AUDIO_LOWBONGO,
	AUDIO_MUTEHICONGA,
	AUDIO_OPENHICONGA,
	AUDIO_HIGHTIMBALE,
	AUDIO_LOWTIMBALE,
	AUDIO_HIGHAGOGO,
	AUDIO_LOWAGOGO,
	AUDIO_CABASSA,
	AUDIO_MUTETRIANGLE,
	AUDIO_OPENTRIANGLE,
	AUDIO_TOTAL_DRUM_COUNT
} AudioDrumIns;

#endif