obj-m := spu_module.o 
spu_module-objs := spu.o
spu_module-objs += SpuReg.o
spu_module-objs += SpuDrv.o
spu_module-objs += Audio.o
spu_module-objs += AudioPhaseTable.o
spu_module-objs += AudioStreamPlayer.o
