#ifndef _MACH_DAC_JACK_H_
#define _MACH_DAC_JACK_H_

#define DACJACK_MAX_VOL_VALUE				31

/* ioctl command */
#define DACJACK_IOC_GETVOL					0x1002
#define DACJACK_IOC_SETVOL					0x1003
#define DACJACK_IOC_SET_OUTPUTMODE			0x1004
#define DACJACK_IOC_GET_OUTPUTMODE			0x1005

#define DACJACK_OUTPUTMODE_SPEAKER			0
#define DACJACK_OUTPUTMODE_HEADPHONE		1

#endif /* _MACH_DAC_JACK_H_ */
