#
# Makefile for the MS card
#

obj-m += gp_mscard.o
gp_mscard-objs := gp_ms.o msproal.o msproal_common.o msproal_icon.o msproal_mc_pro.o msproal_mc_v1.o msproal_mgralif.o msproal_msif.o msproal_pro.o msproal_tpc.o msproal_user.o msproal_v1.o



