#/**************************************************************************
# *                                                                        *
# *         Copyright (c) 2008 by Generalplus Inc.                         *
# *                                                                        *
# *  This software is copyrighted by and is the property of Generalplus    *
# *  Ltd. All rights are reserved by Generalplus Inc.                      *
# *  This software may only be used in accordance with the                 *
# *  corresponding license agreement. Any unauthorized use, duplication,   *
# *  distribution, or disclosure of this software is expressly forbidden.  *
# *                                                                        *
# *  This Copyright notice MUST not be removed or modified without prior   *
# *  written consent of Generalplus Inc.                                   *
# *                                                                        *
# *  Generalplus Inc. reserves the right to modify this software           *
# *  without notice.                                                       *
# *                                                                        *
# *  Generalplus Inc.                                                      *
# *                                                                        *
# *                                                                        *
# **************************************************************************/
TOPDIR := ../../../../../
include $(TOPDIR)sdk/build/core/config.mak

SUBDIRS += aud_demo
SUBDIRS += audrecord
#SUBDIRS += g2dtest
#SUBDIRS += libchunkmem
#SUBDIRS += libImageIF_demo
SUBDIRS += usb
SUBDIRS += spu
SUBDIRS += spu1
SUBDIRS += spu2
SUBDIRS += gimage_decode

all:
	+$(COMMAND)

clean:
	+$(COMMAND)

.PHONY: release
release:
	+$(COMMAND)
