#
# Makefile for the MS card
#

obj-y += nand_debug.o	
	nand_debug-objs := \
	gp_nand_hal/hal_nand.o\
	gp_nand_hal/hal_nand_bch.o\
	gp_nand_hal/hal_nand_smart_id.o\
	gp_nand_hal/hal_nand_bthdr.o\
	nand_innotab.o\
	innotab_nand_debug.o
